# !/usr/bin/env python
# -*- coding:utf-8 -*-　
# @Time : 2023/5/4 22:31
# @Author : sanmaomashi
# @GitHub : https://github.com/sanmaomashi

from fastapi import APIRouter, Query, BackgroundTasks
from fastapi.responses import FileResponse
from edge_tts import Communicate
from tempfile import NamedTemporaryFile
import os

SUMMARY = "语音合成"
POST_DESCRIPTION = "语音合成API\n"

edge_tts_router = APIRouter()


def delete_file(path: str):
    if os.path.exists(path):
        os.remove(path)


VOICES = [
    ('zh-CN-XiaoxiaoNeural, Female', 'zh-CN-XiaoxiaoNeural'),
    ('zh-CN-XiaoyiNeural, Female', 'zh-CN-XiaoyiNeural'),
    ('zh-CN-YunjianNeural, Male', 'zh-CN-YunjianNeural'),
    ('zh-CN-YunxiNeural, Male', 'zh-CN-YunxiNeural'),
    ('zh-CN-YunxiaNeural, Male', 'zh-CN-YunxiaNeural'),
    ('zh-CN-YunyangNeural, Male', 'zh-CN-YunyangNeural'),
    ('zh-CN-liaoning-XiaobeiNeural, Female', 'zh-CN-liaoning-XiaobeiNeural'),
    ('zh-CN-shaanxi-XiaoniNeural, Female', 'zh-CN-shaanxi-XiaoniNeural'),
    ('zh-HK-HiuGaaiNeural, Female', 'zh-HK-HiuGaaiNeural'),
    ('zh-HK-HiuMaanNeural, Female', 'zh-HK-HiuMaanNeural'),
    ('zh-HK-WanLungNeural, Male', 'zh-HK-WanLungNeural'),
    ('zh-TW-HsiaoChenNeural, Female', 'zh-TW-HsiaoChenNeural'),
    ('zh-TW-HsiaoYuNeural, Female', 'zh-TW-HsiaoYuNeural'),
    ('zh-TW-YunJheNeural, Male', 'zh-TW-YunJheNeural'),
    ('af-ZA-AdriNeural, Female', 'af-ZA-AdriNeural'),
    ('af-ZA-WillemNeural, Male', 'af-ZA-WillemNeural'),
    ('am-ET-AmehaNeural, Male', 'am-ET-AmehaNeural'),
    ('am-ET-MekdesNeural, Female', 'am-ET-MekdesNeural'),
    ('ar-AE-FatimaNeural, Female', 'ar-AE-FatimaNeural'),
    ('ar-AE-HamdanNeural, Male', 'ar-AE-HamdanNeural'),
    ('ar-BH-AliNeural, Male', 'ar-BH-AliNeural'),
    ('ar-BH-LailaNeural, Female', 'ar-BH-LailaNeural'),
    ('ar-DZ-AminaNeural, Female', 'ar-DZ-AminaNeural'),
    ('ar-DZ-IsmaelNeural, Male', 'ar-DZ-IsmaelNeural'),
    ('ar-EG-SalmaNeural, Female', 'ar-EG-SalmaNeural'),
    ('ar-EG-ShakirNeural, Male', 'ar-EG-ShakirNeural'),
    ('ar-IQ-BasselNeural, Male', 'ar-IQ-BasselNeural'),
    ('ar-IQ-RanaNeural, Female', 'ar-IQ-RanaNeural'),
    ('ar-JO-SanaNeural, Female', 'ar-JO-SanaNeural'),
    ('ar-JO-TaimNeural, Male', 'ar-JO-TaimNeural'),
    ('ar-KW-FahedNeural, Male', 'ar-KW-FahedNeural'),
    ('ar-KW-NouraNeural, Female', 'ar-KW-NouraNeural'),
    ('ar-LB-LaylaNeural, Female', 'ar-LB-LaylaNeural'),
    ('ar-LB-RamiNeural, Male', 'ar-LB-RamiNeural'),
    ('ar-LY-ImanNeural, Female', 'ar-LY-ImanNeural'),
    ('ar-LY-OmarNeural, Male', 'ar-LY-OmarNeural'),
    ('ar-MA-JamalNeural, Male', 'ar-MA-JamalNeural'),
    ('ar-MA-MounaNeural, Female', 'ar-MA-MounaNeural'),
    ('ar-OM-AbdullahNeural, Male', 'ar-OM-AbdullahNeural'),
    ('ar-OM-AyshaNeural, Female', 'ar-OM-AyshaNeural'),
    ('ar-QA-AmalNeural, Female', 'ar-QA-AmalNeural'),
    ('ar-QA-MoazNeural, Male', 'ar-QA-MoazNeural'),
    ('ar-SA-HamedNeural, Male', 'ar-SA-HamedNeural'),
    ('ar-SA-ZariyahNeural, Female', 'ar-SA-ZariyahNeural'),
    ('ar-SY-AmanyNeural, Female', 'ar-SY-AmanyNeural'),
    ('ar-SY-LaithNeural, Male', 'ar-SY-LaithNeural'),
    ('ar-TN-HediNeural, Male', 'ar-TN-HediNeural'),
    ('ar-TN-ReemNeural, Female', 'ar-TN-ReemNeural'),
    ('ar-YE-MaryamNeural, Female', 'ar-YE-MaryamNeural'),
    ('ar-YE-SalehNeural, Male', 'ar-YE-SalehNeural'),
    ('az-AZ-BabekNeural, Male', 'az-AZ-BabekNeural'),
    ('az-AZ-BanuNeural, Female', 'az-AZ-BanuNeural'),
    ('bg-BG-BorislavNeural, Male', 'bg-BG-BorislavNeural'),
    ('bg-BG-KalinaNeural, Female', 'bg-BG-KalinaNeural'),
    ('bn-BD-NabanitaNeural, Female', 'bn-BD-NabanitaNeural'),
    ('bn-BD-PradeepNeural, Male', 'bn-BD-PradeepNeural'),
    ('bn-IN-BashkarNeural, Male', 'bn-IN-BashkarNeural'),
    ('bn-IN-TanishaaNeural, Female', 'bn-IN-TanishaaNeural'),
    ('bs-BA-GoranNeural, Male', 'bs-BA-GoranNeural'),
    ('bs-BA-VesnaNeural, Female', 'bs-BA-VesnaNeural'),
    ('ca-ES-EnricNeural, Male', 'ca-ES-EnricNeural'),
    ('ca-ES-JoanaNeural, Female', 'ca-ES-JoanaNeural'),
    ('cs-CZ-AntoninNeural, Male', 'cs-CZ-AntoninNeural'),
    ('cs-CZ-VlastaNeural, Female', 'cs-CZ-VlastaNeural'),
    ('cy-GB-AledNeural, Male', 'cy-GB-AledNeural'),
    ('cy-GB-NiaNeural, Female', 'cy-GB-NiaNeural'),
    ('da-DK-ChristelNeural, Female', 'da-DK-ChristelNeural'),
    ('da-DK-JeppeNeural, Male', 'da-DK-JeppeNeural'),
    ('de-AT-IngridNeural, Female', 'de-AT-IngridNeural'),
    ('de-AT-JonasNeural, Male', 'de-AT-JonasNeural'),
    ('de-CH-JanNeural, Male', 'de-CH-JanNeural'),
    ('de-CH-LeniNeural, Female', 'de-CH-LeniNeural'),
    ('de-DE-AmalaNeural, Female', 'de-DE-AmalaNeural'),
    ('de-DE-ConradNeural, Male', 'de-DE-ConradNeural'),
    ('de-DE-KatjaNeural, Female', 'de-DE-KatjaNeural'),
    ('de-DE-KillianNeural, Male', 'de-DE-KillianNeural'),
    ('el-GR-AthinaNeural, Female', 'el-GR-AthinaNeural'),
    ('el-GR-NestorasNeural, Male', 'el-GR-NestorasNeural'),
    ('en-AU-NatashaNeural, Female', 'en-AU-NatashaNeural'),
    ('en-AU-WilliamNeural, Male', 'en-AU-WilliamNeural'),
    ('en-CA-ClaraNeural, Female', 'en-CA-ClaraNeural'),
    ('en-CA-LiamNeural, Male', 'en-CA-LiamNeural'),
    ('en-GB-LibbyNeural, Female', 'en-GB-LibbyNeural'),
    ('en-GB-MaisieNeural, Female', 'en-GB-MaisieNeural'),
    ('en-GB-RyanNeural, Male', 'en-GB-RyanNeural'),
    ('en-GB-SoniaNeural, Female', 'en-GB-SoniaNeural'),
    ('en-GB-ThomasNeural, Male', 'en-GB-ThomasNeural'),
    ('en-HK-SamNeural, Male', 'en-HK-SamNeural'),
    ('en-HK-YanNeural, Female', 'en-HK-YanNeural'),
    ('en-IE-ConnorNeural, Male', 'en-IE-ConnorNeural'),
    ('en-IE-EmilyNeural, Female', 'en-IE-EmilyNeural'),
    ('en-IN-NeerjaExpressiveNeural, Female', 'en-IN-NeerjaExpressiveNeural'),
    ('en-IN-NeerjaNeural, Female', 'en-IN-NeerjaNeural'),
    ('en-IN-PrabhatNeural, Male', 'en-IN-PrabhatNeural'),
    ('en-KE-AsiliaNeural, Female', 'en-KE-AsiliaNeural'),
    ('en-KE-ChilembaNeural, Male', 'en-KE-ChilembaNeural'),
    ('en-NG-AbeoNeural, Male', 'en-NG-AbeoNeural'),
    ('en-NG-EzinneNeural, Female', 'en-NG-EzinneNeural'),
    ('en-NZ-MitchellNeural, Male', 'en-NZ-MitchellNeural'),
    ('en-NZ-MollyNeural, Female', 'en-NZ-MollyNeural'),
    ('en-PH-JamesNeural, Male', 'en-PH-JamesNeural'),
    ('en-PH-RosaNeural, Female', 'en-PH-RosaNeural'),
    ('en-SG-LunaNeural, Female', 'en-SG-LunaNeural'),
    ('en-SG-WayneNeural, Male', 'en-SG-WayneNeural'),
    ('en-TZ-ElimuNeural, Male', 'en-TZ-ElimuNeural'),
    ('en-TZ-ImaniNeural, Female', 'en-TZ-ImaniNeural'),
    ('en-US-AnaNeural, Female', 'en-US-AnaNeural'),
    ('en-US-AriaNeural, Female', 'en-US-AriaNeural'),
    ('en-US-ChristopherNeural, Male', 'en-US-ChristopherNeural'),
    ('en-US-EricNeural, Male', 'en-US-EricNeural'),
    ('en-US-GuyNeural, Male', 'en-US-GuyNeural'),
    ('en-US-JennyNeural, Female', 'en-US-JennyNeural'),
    ('en-US-MichelleNeural, Female', 'en-US-MichelleNeural'),
    ('en-US-RogerNeural, Male', 'en-US-RogerNeural'),
    ('en-US-SteffanNeural, Male', 'en-US-SteffanNeural'),
    ('en-ZA-LeahNeural, Female', 'en-ZA-LeahNeural'),
    ('en-ZA-LukeNeural, Male', 'en-ZA-LukeNeural'),
    ('es-AR-ElenaNeural, Female', 'es-AR-ElenaNeural'),
    ('es-AR-TomasNeural, Male', 'es-AR-TomasNeural'),
    ('es-BO-MarceloNeural, Male', 'es-BO-MarceloNeural'),
    ('es-BO-SofiaNeural, Female', 'es-BO-SofiaNeural'),
    ('es-CL-CatalinaNeural, Female', 'es-CL-CatalinaNeural'),
    ('es-CL-LorenzoNeural, Male', 'es-CL-LorenzoNeural'),
    ('es-CO-GonzaloNeural, Male', 'es-CO-GonzaloNeural'),
    ('es-CO-SalomeNeural, Female', 'es-CO-SalomeNeural'),
    ('es-CR-JuanNeural, Male', 'es-CR-JuanNeural'),
    ('es-CR-MariaNeural, Female', 'es-CR-MariaNeural'),
    ('es-CU-BelkysNeural, Female', 'es-CU-BelkysNeural'),
    ('es-CU-ManuelNeural, Male', 'es-CU-ManuelNeural'),
    ('es-DO-EmilioNeural, Male', 'es-DO-EmilioNeural'),
    ('es-DO-RamonaNeural, Female', 'es-DO-RamonaNeural'),
    ('es-EC-AndreaNeural, Female', 'es-EC-AndreaNeural'),
    ('es-EC-LuisNeural, Male', 'es-EC-LuisNeural'),
    ('es-ES-AlvaroNeural, Male', 'es-ES-AlvaroNeural'),
    ('es-ES-ElviraNeural, Female', 'es-ES-ElviraNeural'),
    ('es-GQ-JavierNeural, Male', 'es-GQ-JavierNeural'),
    ('es-GQ-TeresaNeural, Female', 'es-GQ-TeresaNeural'),
    ('es-GT-AndresNeural, Male', 'es-GT-AndresNeural'),
    ('es-GT-MartaNeural, Female', 'es-GT-MartaNeural'),
    ('es-HN-CarlosNeural, Male', 'es-HN-CarlosNeural'),
    ('es-HN-KarlaNeural, Female', 'es-HN-KarlaNeural'),
    ('es-MX-DaliaNeural, Female', 'es-MX-DaliaNeural'),
    ('es-MX-JorgeNeural, Male', 'es-MX-JorgeNeural'),
    ('es-NI-FedericoNeural, Male', 'es-NI-FedericoNeural'),
    ('es-NI-YolandaNeural, Female', 'es-NI-YolandaNeural'),
    ('es-PA-MargaritaNeural, Female', 'es-PA-MargaritaNeural'),
    ('es-PA-RobertoNeural, Male', 'es-PA-RobertoNeural'),
    ('es-PE-AlexNeural, Male', 'es-PE-AlexNeural'),
    ('es-PE-CamilaNeural, Female', 'es-PE-CamilaNeural'),
    ('es-PR-KarinaNeural, Female', 'es-PR-KarinaNeural'),
    ('es-PR-VictorNeural, Male', 'es-PR-VictorNeural'),
    ('es-PY-MarioNeural, Male', 'es-PY-MarioNeural'),
    ('es-PY-TaniaNeural, Female', 'es-PY-TaniaNeural'),
    ('es-SV-LorenaNeural, Female', 'es-SV-LorenaNeural'),
    ('es-SV-RodrigoNeural, Male', 'es-SV-RodrigoNeural'),
    ('es-US-AlonsoNeural, Male', 'es-US-AlonsoNeural'),
    ('es-US-PalomaNeural, Female', 'es-US-PalomaNeural'),
    ('es-UY-MateoNeural, Male', 'es-UY-MateoNeural'),
    ('es-UY-ValentinaNeural, Female', 'es-UY-ValentinaNeural'),
    ('es-VE-PaolaNeural, Female', 'es-VE-PaolaNeural'),
    ('es-VE-SebastianNeural, Male', 'es-VE-SebastianNeural'),
    ('et-EE-AnuNeural, Female', 'et-EE-AnuNeural'),
    ('et-EE-KertNeural, Male', 'et-EE-KertNeural'),
    ('fa-IR-DilaraNeural, Female', 'fa-IR-DilaraNeural'),
    ('fa-IR-FaridNeural, Male', 'fa-IR-FaridNeural'),
    ('fi-FI-HarriNeural, Male', 'fi-FI-HarriNeural'),
    ('fi-FI-NooraNeural, Female', 'fi-FI-NooraNeural'),
    ('fil-PH-AngeloNeural, Male', 'fil-PH-AngeloNeural'),
    ('fil-PH-BlessicaNeural, Female', 'fil-PH-BlessicaNeural'),
    ('fr-BE-CharlineNeural, Female', 'fr-BE-CharlineNeural'),
    ('fr-BE-GerardNeural, Male', 'fr-BE-GerardNeural'),
    ('fr-CA-AntoineNeural, Male', 'fr-CA-AntoineNeural'),
    ('fr-CA-JeanNeural, Male', 'fr-CA-JeanNeural'),
    ('fr-CA-SylvieNeural, Female', 'fr-CA-SylvieNeural'),
    ('fr-CH-ArianeNeural, Female', 'fr-CH-ArianeNeural'),
    ('fr-CH-FabriceNeural, Male', 'fr-CH-FabriceNeural'),
    ('fr-FR-DeniseNeural, Female', 'fr-FR-DeniseNeural'),
    ('fr-FR-EloiseNeural, Female', 'fr-FR-EloiseNeural'),
    ('fr-FR-HenriNeural, Male', 'fr-FR-HenriNeural'),
    ('ga-IE-ColmNeural, Male', 'ga-IE-ColmNeural'),
    ('ga-IE-OrlaNeural, Female', 'ga-IE-OrlaNeural'),
    ('gl-ES-RoiNeural, Male', 'gl-ES-RoiNeural'),
    ('gl-ES-SabelaNeural, Female', 'gl-ES-SabelaNeural'),
    ('gu-IN-DhwaniNeural, Female', 'gu-IN-DhwaniNeural'),
    ('gu-IN-NiranjanNeural, Male', 'gu-IN-NiranjanNeural'),
    ('he-IL-AvriNeural, Male', 'he-IL-AvriNeural'),
    ('he-IL-HilaNeural, Female', 'he-IL-HilaNeural'),
    ('hi-IN-MadhurNeural, Male', 'hi-IN-MadhurNeural'),
    ('hi-IN-SwaraNeural, Female', 'hi-IN-SwaraNeural'),
    ('hr-HR-GabrijelaNeural, Female', 'hr-HR-GabrijelaNeural'),
    ('hr-HR-SreckoNeural, Male', 'hr-HR-SreckoNeural'),
    ('hu-HU-NoemiNeural, Female', 'hu-HU-NoemiNeural'),
    ('hu-HU-TamasNeural, Male', 'hu-HU-TamasNeural'),
    ('id-ID-ArdiNeural, Male', 'id-ID-ArdiNeural'),
    ('id-ID-GadisNeural, Female', 'id-ID-GadisNeural'),
    ('is-IS-GudrunNeural, Female', 'is-IS-GudrunNeural'),
    ('is-IS-GunnarNeural, Male', 'is-IS-GunnarNeural'),
    ('it-IT-DiegoNeural, Male', 'it-IT-DiegoNeural'),
    ('it-IT-ElsaNeural, Female', 'it-IT-ElsaNeural'),
    ('it-IT-IsabellaNeural, Female', 'it-IT-IsabellaNeural'),
    ('ja-JP-KeitaNeural, Male', 'ja-JP-KeitaNeural'),
    ('ja-JP-NanamiNeural, Female', 'ja-JP-NanamiNeural'),
    ('jv-ID-DimasNeural, Male', 'jv-ID-DimasNeural'),
    ('jv-ID-SitiNeural, Female', 'jv-ID-SitiNeural'),
    ('ka-GE-EkaNeural, Female', 'ka-GE-EkaNeural'),
    ('ka-GE-GiorgiNeural, Male', 'ka-GE-GiorgiNeural'),
    ('kk-KZ-AigulNeural, Female', 'kk-KZ-AigulNeural'),
    ('kk-KZ-DauletNeural, Male', 'kk-KZ-DauletNeural'),
    ('km-KH-PisethNeural, Male', 'km-KH-PisethNeural'),
    ('km-KH-SreymomNeural, Female', 'km-KH-SreymomNeural'),
    ('kn-IN-GaganNeural, Male', 'kn-IN-GaganNeural'),
    ('kn-IN-SapnaNeural, Female', 'kn-IN-SapnaNeural'),
    ('ko-KR-InJoonNeural, Male', 'ko-KR-InJoonNeural'),
    ('ko-KR-SunHiNeural, Female', 'ko-KR-SunHiNeural'),
    ('lo-LA-ChanthavongNeural, Male', 'lo-LA-ChanthavongNeural'),
    ('lo-LA-KeomanyNeural, Female', 'lo-LA-KeomanyNeural'),
    ('lt-LT-LeonasNeural, Male', 'lt-LT-LeonasNeural'),
    ('lt-LT-OnaNeural, Female', 'lt-LT-OnaNeural'),
    ('lv-LV-EveritaNeural, Female', 'lv-LV-EveritaNeural'),
    ('lv-LV-NilsNeural, Male', 'lv-LV-NilsNeural'),
    ('mk-MK-AleksandarNeural, Male', 'mk-MK-AleksandarNeural'),
    ('mk-MK-MarijaNeural, Female', 'mk-MK-MarijaNeural'),
    ('ml-IN-MidhunNeural, Male', 'ml-IN-MidhunNeural'),
    ('ml-IN-SobhanaNeural, Female', 'ml-IN-SobhanaNeural'),
    ('mn-MN-BataaNeural, Male', 'mn-MN-BataaNeural'),
    ('mn-MN-YesuiNeural, Female', 'mn-MN-YesuiNeural'),
    ('mr-IN-AarohiNeural, Female', 'mr-IN-AarohiNeural'),
    ('mr-IN-ManoharNeural, Male', 'mr-IN-ManoharNeural'),
    ('ms-MY-OsmanNeural, Male', 'ms-MY-OsmanNeural'),
    ('ms-MY-YasminNeural, Female', 'ms-MY-YasminNeural'),
    ('mt-MT-GraceNeural, Female', 'mt-MT-GraceNeural'),
    ('mt-MT-JosephNeural, Male', 'mt-MT-JosephNeural'),
    ('my-MM-NilarNeural, Female', 'my-MM-NilarNeural'),
    ('my-MM-ThihaNeural, Male', 'my-MM-ThihaNeural'),
    ('nb-NO-FinnNeural, Male', 'nb-NO-FinnNeural'),
    ('nb-NO-PernilleNeural, Female', 'nb-NO-PernilleNeural'),
    ('ne-NP-HemkalaNeural, Female', 'ne-NP-HemkalaNeural'),
    ('ne-NP-SagarNeural, Male', 'ne-NP-SagarNeural'),
    ('nl-BE-ArnaudNeural, Male', 'nl-BE-ArnaudNeural'),
    ('nl-BE-DenaNeural, Female', 'nl-BE-DenaNeural'),
    ('nl-NL-ColetteNeural, Female', 'nl-NL-ColetteNeural'),
    ('nl-NL-FennaNeural, Female', 'nl-NL-FennaNeural'),
    ('nl-NL-MaartenNeural, Male', 'nl-NL-MaartenNeural'),
    ('pl-PL-MarekNeural, Male', 'pl-PL-MarekNeural'),
    ('pl-PL-ZofiaNeural, Female', 'pl-PL-ZofiaNeural'),
    ('ps-AF-GulNawazNeural, Male', 'ps-AF-GulNawazNeural'),
    ('ps-AF-LatifaNeural, Female', 'ps-AF-LatifaNeural'),
    ('pt-BR-AntonioNeural, Male', 'pt-BR-AntonioNeural'),
    ('pt-BR-FranciscaNeural, Female', 'pt-BR-FranciscaNeural'),
    ('pt-PT-DuarteNeural, Male', 'pt-PT-DuarteNeural'),
    ('pt-PT-RaquelNeural, Female', 'pt-PT-RaquelNeural'),
    ('ro-RO-AlinaNeural, Female', 'ro-RO-AlinaNeural'),
    ('ro-RO-EmilNeural, Male', 'ro-RO-EmilNeural'),
    ('ru-RU-DmitryNeural, Male', 'ru-RU-DmitryNeural'),
    ('ru-RU-SvetlanaNeural, Female', 'ru-RU-SvetlanaNeural'),
    ('si-LK-SameeraNeural, Male', 'si-LK-SameeraNeural'),
    ('si-LK-ThiliniNeural, Female', 'si-LK-ThiliniNeural'),
    ('sk-SK-LukasNeural, Male', 'sk-SK-LukasNeural'),
    ('sk-SK-ViktoriaNeural, Female', 'sk-SK-ViktoriaNeural'),
    ('sl-SI-PetraNeural, Female', 'sl-SI-PetraNeural'),
    ('sl-SI-RokNeural, Male', 'sl-SI-RokNeural'),
    ('so-SO-MuuseNeural, Male', 'so-SO-MuuseNeural'),
    ('so-SO-UbaxNeural, Female', 'so-SO-UbaxNeural'),
    ('sq-AL-AnilaNeural, Female', 'sq-AL-AnilaNeural'),
    ('sq-AL-IlirNeural, Male', 'sq-AL-IlirNeural'),
    ('sr-RS-NicholasNeural, Male', 'sr-RS-NicholasNeural'),
    ('sr-RS-SophieNeural, Female', 'sr-RS-SophieNeural'),
    ('su-ID-JajangNeural, Male', 'su-ID-JajangNeural'),
    ('su-ID-TutiNeural, Female', 'su-ID-TutiNeural'),
    ('sv-SE-MattiasNeural, Male', 'sv-SE-MattiasNeural'),
    ('sv-SE-SofieNeural, Female', 'sv-SE-SofieNeural'),
    ('sw-KE-RafikiNeural, Male', 'sw-KE-RafikiNeural'),
    ('sw-KE-ZuriNeural, Female', 'sw-KE-ZuriNeural'),
    ('sw-TZ-DaudiNeural, Male', 'sw-TZ-DaudiNeural'),
    ('sw-TZ-RehemaNeural, Female', 'sw-TZ-RehemaNeural'),
    ('ta-IN-PallaviNeural, Female', 'ta-IN-PallaviNeural'),
    ('ta-IN-ValluvarNeural, Male', 'ta-IN-ValluvarNeural'),
    ('ta-LK-KumarNeural, Male', 'ta-LK-KumarNeural'),
    ('ta-LK-SaranyaNeural, Female', 'ta-LK-SaranyaNeural'),
    ('ta-MY-KaniNeural, Female', 'ta-MY-KaniNeural'),
    ('ta-MY-SuryaNeural, Male', 'ta-MY-SuryaNeural'),
    ('ta-SG-AnbuNeural, Male', 'ta-SG-AnbuNeural'),
    ('ta-SG-NaliniNeural, Female', 'ta-SG-NaliniNeural'),
    ('te-IN-SatyaNeural, Female', 'te-IN-SatyaNeural'),
    ('te-IN-ShravanNeural, Male', 'te-IN-ShravanNeural'),
    ('th-TH-PhiravichNeural, Male', 'th-TH-PhiravichNeural'),
    ('th-TH-PremwadeeNeural, Female', 'th-TH-PremwadeeNeural'),
    ('tl-PH-JamesNeural, Male', 'tl-PH-JamesNeural'),
    ('tl-PH-RosaNeural, Female', 'tl-PH-RosaNeural'),
    ('tr-TR-AhmetNeural, Male', 'tr-TR-AhmetNeural'),
    ('tr-TR-DemirNeural, Male', 'tr-TR-DemirNeural'),
    ('tr-TR-EmelNeural, Female', 'tr-TR-EmelNeural'),
    ('uk-UA-OstapNeural, Male', 'uk-UA-OstapNeural'),
    ('uk-UA-PolinaNeural, Female', 'uk-UA-PolinaNeural'),
    ('ur-PK-AsadNeural, Male', 'ur-PK-AsadNeural'),
    ('ur-PK-SarahNeural, Female', 'ur-PK-SarahNeural'),
    ('vi-VN-HoaiMyNeural, Female', 'vi-VN-HoaiMyNeural'),
    ('vi-VN-NamMinhNeural, Male', 'vi-VN-NamMinhNeural'),
    ('xh-ZA-LwaziNeural, Male', 'xh-ZA-LwaziNeural'),
    ('xh-ZA-SiweNeural, Female', 'xh-ZA-SiweNeural'),
    ('yo-NG-AdeolaNeural, Female', 'yo-NG-AdeolaNeural'),
    ('yo-NG-BolajiNeural, Male', 'yo-NG-BolajiNeural'),
    ('zu-ZA-AyandaNeural, Female', 'zu-ZA-AyandaNeural'),
    ('zu-ZA-LungaNeural, Male', 'zu-ZA-LungaNeural'),
    ('zu-ZA-ThandoNeural, Female', 'zu-ZA-ThandoNeural'),
    ('zzu-ZA-ThembaNeural, Male', 'zu-ZA-ThembaNeural'),
]

VOICE_CHOICES, VOICE_VALUES = zip(*VOICES)


@edge_tts_router.post("/edge_tts/", summary=SUMMARY, description=POST_DESCRIPTION,
                      response_description="语音合成结果")
async def predict(
        background_tasks: BackgroundTasks,
        text: str = Query(..., description='输入要生成的文本。'),
        voice: str = Query(VOICE_CHOICES[0], description="选择的语音。", enum=VOICE_CHOICES),
        rate: str = Query("+0%", description='语速，例如"+10%"。'),
        volume: str = Query("+0%", description='音量，例如"+10%"。')
):
    voice = VOICE_VALUES[VOICE_CHOICES.index(voice)]  # convert display value to actual value
    communicate = Communicate(text=text, voice=voice, rate=rate, volume=volume)
    temp_file = NamedTemporaryFile(delete=False, suffix=".mp3")
    filename = temp_file.name
    await communicate.save(filename)
    background_tasks.add_task(delete_file, filename)

    response = FileResponse(filename, media_type="audio/mpeg", filename="output.mp3",
                            headers={"Content-Disposition": "attachment; filename=output.mp3"})
    return response
